### ISSUE TITLE
Usage of custom java code

### ISSUE THREAD

**Issue by ewoutreinders** [lsc-project/lsc#23]
I was reading about the lsc project and I am really interested in the OpenLDAP to AD migration/synchronization part. I also read that it could synchronise everything from OpenLDAP to AD except an encrypted password (which also seems logical to me since it is saved as an encrypted value in OpenLDAP). I also read in the documentation that it works when password is stored as plain text.

However, I have both keys (public and private keys) available from the OpenLDAP server and also know the algorithm, so I was thinking about to write some custom java code which decrypt the password value before synchronising it to AD. I also read in the README that it is possible to write some custom java code in lsc.

My question is; What is the best approach/where to start? Do I have to write a java plugin for lsc or is it easier to  modify something within the project itself? Is there also an example available which shows how to use custom java code with some custom specific synchronisation? Some documentation available which classes I need to extend?

**Comment by soisik** [comment]
Hi,

You may consider using LSC built-in tools for symmetric encryption : 
https://lsc-project.org/documentation/2.1/configuration/syncoptions/security

As for your question, you can call custom java classes from a JS script to send clear text password instead of encrypted one. Just reference your class in LSC configuration XML file in the customLibrary attribute, cf https://lsc-project.org/documentation/2.1/configuration/tasks :

'<customLibrary>
'   <string>org.apache.commons.codec.binary.Base64</string>
'</customLibrary>

And use it to do your transformation : 
'<forceValues>
'    <string>custom[0]. encodeBase64(“blabla”)</string>
' </forceValues>

The jar containing your class must be in LSC lib/ directory

I got most of these information https://lists.lsc-project.org/pipermail/lsc-users/2013-November/001635.html, I haven't tested it myself. Please let us know how it went.

Also, you will get more support from LSC community using the mailing list lsc-users@lists.lsc-project.org (register in https://lists.lsc-project.org/) rather than the bug tracker.

**Comment by ewoutreinders** [comment]
Tnx for the fast and clear response! 👍 I will try it out. When I ran into more problems, I will use the mailing list.
